model:
  swinir:
    target: model.swinir.SwinIR
    params:
      img_size: 64
      patch_size: 1
      in_chans: 3
      embed_dim: 180
      depths: [6, 6, 6, 6, 6, 6, 6, 6]
      num_heads: [6, 6, 6, 6, 6, 6, 6, 6]
      window_size: 8
      mlp_ratio: 2
      sf: 8
      img_range: 1.0
      upsampler: "nearest+conv"
      resi_connection: "1conv"
      unshuffle: True
      unshuffle_scale: 8
  
  clsnet:
    target: model.resnet.ResNet
    params:
      type: 18
      num_classes: 200

dataset:  
  train:
    target: datasets.classification.DegradedClassificationDataset
    params:
      root: datasets/source/CUB200/train
      file_backend_cfg:
        target: datasets.file_backend.HardDiskBackend
      gt_size: 576
      out_size: 512
      hflip: true
      rotation: false
      crop_type: random
      blur_kernel_size: 41
      kernel_list: ['iso', 'aniso']
      kernel_prob: [0.5, 0.5]
      blur_sigma: [0.1, 8]
      downsample_range: [1, 16]
      noise_range: [0, 10]
      jpeg_range: [50, 100]
  val:
    target: datasets.classification.PairedClassificationDataset
    params:
      root: datasets/source/CUB200/val-deg
      file_backend_cfg:
        target: datasets.file_backend.HardDiskBackend

train:
  seed: 123
  precision: ~ #fp16
  exp_dir: experiments/cls/cub200/003_swinir
  resume_swinir: experiments/cls/cub200/002_swinir-pre/checkpoints/swinir_last.pt
  resume_clsnet: experiments/cls/cub200/000_oracle/checkpoints/clsnet_last.pt
  strict_load: true
  # training options
  learning_rate: 5e-3
  batch_size: 32
  num_workers: 16
  train_steps: 10000
  log_every: 50
  ckpt_every: 10000
  image_every: 1000
val:
  batch_size: 32
  num_workers: 16
  val_every: 1000
