model:
  swinir:
    target: model.swinir.SwinIR
    params:
      img_size: 64
      patch_size: 1
      in_chans: 3
      embed_dim: 180
      depths: [6, 6, 6, 6, 6, 6, 6, 6]
      num_heads: [6, 6, 6, 6, 6, 6, 6, 6]
      window_size: 8
      mlp_ratio: 2
      sf: 8
      img_range: 1.0
      upsampler: "nearest+conv"
      resi_connection: "1conv"
      unshuffle: True
      unshuffle_scale: 8

dataset:
  is_coco: true
  train:
    target: datasets.detection_cocov2.DegradedDetectionDatasetCocov2
    params:
      root: datasets/source/COCO
      image_set: train
      file_backend_cfg:
        target: datasets.file_backend.HardDiskBackend
      gt_size: 512
      out_size: 512
      hflip: true
      rotation: false
      crop_type: none
      
      blur_kernel_size: 21
      kernel_list: ['iso', 'aniso', 'generalized_iso', 'generalized_aniso', 'plateau_iso', 'plateau_aniso']
      kernel_prob: [0.45, 0.25, 0.12, 0.03, 0.12, 0.03]
      sinc_prob: 0.1
      blur_sigma: [0.2, 3]
      betag_range: [0.5, 4]
      betap_range: [1, 2]

      blur_kernel_size2: 21
      kernel_list2: ['iso', 'aniso', 'generalized_iso', 'generalized_aniso', 'plateau_iso', 'plateau_aniso']
      kernel_prob2: [0.45, 0.25, 0.12, 0.03, 0.12, 0.03]
      sinc_prob2: 0.1
      blur_sigma2: [0.2, 1.5]
      betag_range2: [0.5, 4]
      betap_range2: [1, 2]

      final_sinc_prob: 0.8
  batch_transform:
    target: datasets.detection_cocov2.RealESRGANBatchTransform
    params:
      hq_key: hq
      extra_keys: []
      use_sharpener: true
      # Queue size of training pool, this should be multiples of batch_size (per GPU).
      queue_size: 0
      # the first degradation process
      resize_prob: [0.2, 0.7, 0.1] # up, down, keep
      resize_range: [0.15, 1.5]
      gaussian_noise_prob: 0.5
      noise_range: [1, 30]
      poisson_scale_range: [0.05, 3]
      gray_noise_prob: 0.4
      jpeg_range: [30, 95]

      # the second degradation process
      stage2_scale: 4
      second_blur_prob: 0.8
      resize_prob2: [0.3, 0.4, 0.3] # up, down, keep
      resize_range2: [0.3, 1.2]
      gaussian_noise_prob2: 0.5
      noise_range2: [1, 25]
      poisson_scale_range2: [0.05, 2.5]
      gray_noise_prob2: 0.4
      jpeg_range2: [30, 95]

      resize_back: true
  val:
    target: datasets.detection_coco.PairedDetectionDatasetCoco
    params:
      root: datasets/source/COCO
      path: val2017-deg-realesrgan/lq
      gt_size: 512
      file_backend_cfg:
        target: datasets.file_backend.HardDiskBackend

train:
  seed: 231
  precision: fp16
  exp_dir: experiments/det/coco/100_swinir-pre-v2
  resume_swinir: weights/codeformer_swinir.ckpt
  strict_load: true
  aspect_ratio_group_factor : 3
  learning_rate: 2.5e-5
  batch_size: 32
  num_workers: 16
  train_steps: 100000
  log_every: 50
  ckpt_every: 20000
  image_every: 500
val:
  batch_size: -1  # Automatically set to the number of available GPUs
  num_workers: 16
  val_every: 20000
