model:
  pre_restoration: True
  swinir:
    target: model.swinir.SwinIR
    params:
      img_size: 64
      patch_size: 1
      in_chans: 3
      embed_dim: 180
      depths: [6, 6, 6, 6, 6, 6, 6, 6]
      num_heads: [6, 6, 6, 6, 6, 6, 6, 6]
      window_size: 8
      mlp_ratio: 2
      sf: 8
      img_range: 1.0
      upsampler: "nearest+conv"
      resi_connection: "1conv"
      unshuffle: True
      unshuffle_scale: 8

  cldm:
    target: model.cldm.ControlLDM
    params:
      latent_scale_factor: 0.18215
      unet_cfg:
        use_checkpoint: True
        image_size: 32 # unused
        in_channels: 4
        out_channels: 4
        model_channels: 320
        attention_resolutions: [ 4, 2, 1 ]
        num_res_blocks: 2
        channel_mult: [ 1, 2, 4, 4 ]
        num_head_channels: 64 # need to fix for flash-attn
        use_spatial_transformer: True
        use_linear_in_transformer: True
        transformer_depth: 1
        context_dim: 1024
        legacy: False
      vae_cfg:
        train_decoder: true
        embed_dim: 4
        ddconfig:
          double_z: true
          z_channels: 4
          resolution: 256
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult:
          - 1
          - 2
          - 4
          - 4
          num_res_blocks: 2
          attn_resolutions: []
          dropout: 0.0
      clip_cfg:
        embed_dim: 1024
        vision_cfg:
          image_size: 224
          layers: 32
          width: 1280
          head_width: 80
          patch_size: 14
        text_cfg:
          context_length: 77
          vocab_size: 49408
          width: 1024
          heads: 16
          layers: 24
        layer: "penultimate"
      controlnet_cfg:
        use_checkpoint: True
        image_size: 32 # unused
        in_channels: 4
        hint_channels: 4
        model_channels: 320
        attention_resolutions: [ 4, 2, 1 ]
        num_res_blocks: 2
        channel_mult: [ 1, 2, 4, 4 ]
        num_head_channels: 64 # need to fix for flash-attn
        use_spatial_transformer: True
        use_linear_in_transformer: True
        transformer_depth: 1
        context_dim: 1024
        legacy: False

  teacher_detnet:
    target: model.faster_rcnn.fasterrcnn_resnet50_fpn_v2
    params:
      weights_backbone: ResNet50_Weights.IMAGENET1K_V2
      num_classes: 91
  
  detnet:
    target: model.faster_rcnn.fasterrcnn_resnet50_fpn_v2
    params:
      weights_backbone: ResNet50_Weights.IMAGENET1K_V2
      num_classes: 91

  diffusion:
    target: model.gaussian_diffusion.Diffusion
    params:
      linear_start: 0.00085
      linear_end: 0.0120
      timesteps: 1000

dataset:
  is_coco: true
  train:
    target: datasets.detection_cocov2.DegradedDetectionDatasetCocov2
    params:
      root: datasets/source/COCO
      image_set: train
      file_backend_cfg:
        target: datasets.file_backend.HardDiskBackend
      gt_size: 512
      out_size: 512
      hflip: true
      rotation: false
      crop_type: none
      
      blur_kernel_size: 21
      kernel_list: ['iso', 'aniso', 'generalized_iso', 'generalized_aniso', 'plateau_iso', 'plateau_aniso']
      kernel_prob: [0.45, 0.25, 0.12, 0.03, 0.12, 0.03]
      sinc_prob: 0.1
      blur_sigma: [0.2, 3]
      betag_range: [0.5, 4]
      betap_range: [1, 2]

      blur_kernel_size2: 21
      kernel_list2: ['iso', 'aniso', 'generalized_iso', 'generalized_aniso', 'plateau_iso', 'plateau_aniso']
      kernel_prob2: [0.45, 0.25, 0.12, 0.03, 0.12, 0.03]
      sinc_prob2: 0.1
      blur_sigma2: [0.2, 1.5]
      betag_range2: [0.5, 4]
      betap_range2: [1, 2]

      final_sinc_prob: 0.8
  batch_transform:
    target: datasets.detection_cocov2.RealESRGANBatchTransform
    params:
      hq_key: hq
      extra_keys: []
      use_sharpener: true
      # Queue size of training pool, this should be multiples of batch_size (per GPU).
      queue_size: 0
      # the first degradation process
      resize_prob: [0.2, 0.7, 0.1] # up, down, keep
      resize_range: [0.15, 1.5]
      gaussian_noise_prob: 0.5
      noise_range: [1, 30]
      poisson_scale_range: [0.05, 3]
      gray_noise_prob: 0.4
      jpeg_range: [30, 95]

      # the second degradation process
      stage2_scale: 4
      second_blur_prob: 0.8
      resize_prob2: [0.3, 0.4, 0.3] # up, down, keep
      resize_range2: [0.3, 1.2]
      gaussian_noise_prob2: 0.5
      noise_range2: [1, 25]
      poisson_scale_range2: [0.05, 2.5]
      gray_noise_prob2: 0.4
      jpeg_range2: [30, 95]

      resize_back: true
  val:
    target: datasets.detection_coco.PairedDetectionDatasetCoco
    params:
      root: datasets/source/COCO
      path: val2017-deg-realesrgan/lq
      gt_size: 512
      file_backend_cfg:
        target: datasets.file_backend.HardDiskBackend

train:
  seed: 132
  precision: fp16
  exp_dir: experiments/det/coco/101_edtr-s4-r50v2
  sd_path: weights/v2-1_512-ema-pruned.ckpt
  resume_swinir: experiments/det/coco/100_swinir-pre-v2/checkpoints/swinir_last.pt
  resume_cldm: experiments/det/coco/001_edtr-s4-r50/checkpoints/cldm_last.pt
  resume_decoder: experiments/det/coco/001_edtr-s4-r50/checkpoints/decoder_last.pt
  resume_detnet: experiments/det/coco/001_edtr-s4-r50/checkpoints/detnet_last.pt
  resume_teacher_detnet: weights/FasterRCNN_ResNet50_FPN_V2_Weights_COCO_V1.pt
  strict_load: true
  aspect_ratio_group_factor : 3
  learning_rate_edtr: 5e-5
  learning_rate_detnet: 1e-4
  start_timestep: 200
  num_timesteps: 4
  default_prompt: ""
  weight_hlf: 1.0
  weight_det: 1.0
  weight_fm: 0.2
  batch_size: 16
  num_workers: 16
  train_steps: 200000
  log_every: 500
  ckpt_every: 10000
  image_every: 500
val:
  batch_size: -1  # Automatically set to the number of available GPUs
  num_workers: 16
  val_every: 25000
  start_timestep: 200
  num_timesteps: 4
  default_prompt: ""
