model:
  pre_restoration: True
  swinir:
    target: model.swinir.SwinIR
    params:
      img_size: 64
      patch_size: 1
      in_chans: 3
      embed_dim: 180
      depths: [6, 6, 6, 6, 6, 6, 6, 6]
      num_heads: [6, 6, 6, 6, 6, 6, 6, 6]
      window_size: 8
      mlp_ratio: 2
      sf: 8
      img_range: 1.0
      upsampler: "nearest+conv"
      resi_connection: "1conv"
      unshuffle: True
      unshuffle_scale: 8

  cldm:
    target: model.cldm.ControlLDM
    params:
      latent_scale_factor: 0.18215
      unet_cfg:
        use_checkpoint: True
        image_size: 32 # unused
        in_channels: 4
        out_channels: 4
        model_channels: 320
        attention_resolutions: [ 4, 2, 1 ]
        num_res_blocks: 2
        channel_mult: [ 1, 2, 4, 4 ]
        num_head_channels: 64 # need to fix for flash-attn
        use_spatial_transformer: True
        use_linear_in_transformer: True
        transformer_depth: 1
        context_dim: 1024
        legacy: False
      vae_cfg:
        train_decoder: true
        embed_dim: 4
        ddconfig:
          double_z: true
          z_channels: 4
          resolution: 256
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult:
          - 1
          - 2
          - 4
          - 4
          num_res_blocks: 2
          attn_resolutions: []
          dropout: 0.0
      clip_cfg:
        embed_dim: 1024
        vision_cfg:
          image_size: 224
          layers: 32
          width: 1280
          head_width: 80
          patch_size: 14
        text_cfg:
          context_length: 77
          vocab_size: 49408
          width: 1024
          heads: 16
          layers: 24
        layer: "penultimate"
      controlnet_cfg:
        use_checkpoint: True
        image_size: 32 # unused
        in_channels: 4
        hint_channels: 4
        model_channels: 320
        attention_resolutions: [ 4, 2, 1 ]
        num_res_blocks: 2
        channel_mult: [ 1, 2, 4, 4 ]
        num_head_channels: 64 # need to fix for flash-attn
        use_spatial_transformer: True
        use_linear_in_transformer: True
        transformer_depth: 1
        context_dim: 1024
        legacy: False

  teacher_detnet:
    target: model.faster_rcnn.fasterrcnn_mobilenet_v3_large_fpn
    params:
      weights_backbone: MobileNet_V3_Large_Weights.IMAGENET1K_V1
      num_classes: 21
  
  detnet:
    target: model.faster_rcnn.fasterrcnn_mobilenet_v3_large_fpn
    params:
      weights_backbone: MobileNet_V3_Large_Weights.IMAGENET1K_V1
      num_classes: 21

  diffusion:
    target: model.gaussian_diffusion.Diffusion
    params:
      linear_start: 0.00085
      linear_end: 0.0120
      timesteps: 1000

dataset:  
  train:
    target: datasets.detection.DegradedDetectionDataset
    params:
      root: datasets/source/VOC
      year: '2012'
      image_set: train
      file_backend_cfg:
        target: datasets.file_backend.HardDiskBackend
      gt_size: 512
      out_size: 512
      hflip: true
      rotation: false
      crop_type: none
      blur_kernel_size: 41
      kernel_list: ['iso', 'aniso']
      kernel_prob: [0.5, 0.5]
      blur_sigma: [0.1, 8]
      downsample_range: [1, 16]
      noise_range: [0, 10]
      jpeg_range: [50, 100]
  val:
    target: datasets.detection.PairedDetectionDataset
    params:
      root: datasets/source/VOC
      path: JPEGImagesDet-deg
      gt_size: 512
      year: '2012'
      image_set: val
      file_backend_cfg:
        target: datasets.file_backend.HardDiskBackend

train:
  seed: 231
  precision: fp16
  exp_dir: experiments/det/voc2012/007_edtr-s4
  sd_path: weights/v2-1_512-ema-pruned.ckpt
  resume_cldm: ~
  resume_swinir: experiments/det/voc2012/002_swinir-pre/checkpoints/swinir_last.pt
  resume_teacher_detnet: experiments/det/voc2012/000_oracle/checkpoints/detnet_last.pt
  resume_detnet: experiments/det/voc2012/000_oracle/checkpoints/detnet_last.pt
  strict_load: true
  aspect_ratio_group_factor : 3
  learning_rate_edtr: 1e-4
  learning_rate_detnet: 5e-3
  start_timestep: 200
  num_timesteps: 4
  default_prompt: ""
  weight_hlf: 0.5
  weight_det: 1.0
  weight_fm: 0.2
  batch_size: 16
  num_workers: 16
  train_steps: 10000
  log_every: 50
  ckpt_every: 10000
  image_every: 500
val:
  batch_size: -1  # Automatically set to the number of available GPUs
  num_workers: 16
  val_every: 2000
  start_timestep: 200
  num_timesteps: 4
  default_prompt: ""
